name: Deploy node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t victor823543/ranking-room-api .
      - name: Publish Image to Docker Hub
        run: docker push victor823543/ranking-room-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull --quiet victor823543/ranking-room-api:latest
      - name: Stop and Remove Old Container
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true
      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}" >> .env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
          echo "S3_REGION=${{ secrets.S3_REGION }}" >> .env
          echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "NODE_ENV=production" >> .env
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container --env-file .env victor823543/ranking-room-api
      - name: Remove .env file
        run: rm .env
